### ISSUE TITLE
cause: Error: connect ECONNREFUSED 127.0.0.1:8000

### ISSUE THREAD

**Issue by Tryici** [Kingfish404/segment-anything-webui#10]
![image](https://github.com/Kingfish404/segment-anything-webui/assets/61930737/740b1cb3-d047-4a8f-9f16-ff6b9c09db66)
i just install as like in readme.md, however it goes wrong like this. how to solve it, thank you!

**Comment by Kingfish404** [comment]
Have you booted the backend at step 2?

```shell
python3 scripts/server.py   # webui backend
npm run dev                 # interactive webui frontend
```
