### ISSUE TITLE
error - Error [TypeError]: fetch failed

### ISSUE THREAD

**Issue by zhangyuereal** [Kingfish404/segment-anything-webui#2]
<img width="602" alt="1681571749592" src="https://user-images.githubusercontent.com/34960749/232233561-8b5e07c0-e604-4bda-a129-b9909162f046.png">
在前端做任何操作，都会报如下错误

**Comment by Kingfish404** [comment]
这是一个前后端分离项目，你只启动了前端部分，还需要配置并启动 SAM 后端，具体细节参考 README.md Usage的步骤 1，2

https://github.com/Kingfish404/segment-anything-webui/blob/5815878396046541bb85739a232e998af5e84ebf/README.md?plain=1#L41
