### ISSUE TITLE
Type error: Object is possibly 'undefined'.

### ISSUE THREAD

**Issue by chester256** [Kingfish404/segment-anything-webui#5]
![image](https://github.com/Kingfish404/segment-anything-webui/assets/18751402/fdd47c81-0cb0-45db-9864-663673e91e3e)

**Comment by Kingfish404** [comment]
Two Docker build at [05dab5e](https://github.com/Kingfish404/segment-anything-webui/commit/05dab5e41908bc48aa172e4cd400746cf587e04b)
- https://hub.docker.com/repository/docker/kingfish404/segment-anything-webui-server
- https://hub.docker.com/repository/docker/kingfish404/segment-anything-webui-frontend

Device:
```
Darwin XXX 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
```

I need more information to debug (such as `uname -a`), or you can choose to use the Image that I built.

**Comment by Kingfish404** [comment]
No more progressing
