### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by m23project** [Kingfish404/segment-anything-webui#8]
Hi,

thanks for your work :-)

I'm trying to setup segment-anything-webui on Debian 12 and found that in "cd script" is missing an "s". It should be "cd scripts".

When trying to run "pip3 install -r requirements.txt" it gives me:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.16.1 requires torch==2.1.1, but you have torch 2.0.0 which is incompatible.

PS I'm running it in a fresh venv.

"pip3 install torch numpy 'uvicorn[standard]' fastapi pydantic python-multipart Pillow click" works.

**Comment by Kingfish404** [comment]
Thanks! And welcome for the pull request.

**Comment by Kingfish404** [comment]
937f65b should fix this.
